<a href="https://colab.research.google.com/github/Rahmasamy/Rahmasamy/blob/main/classificationmodels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install AutoViz

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: AutoViz in /usr/local/lib/python3.10/dist-packages (0.1.603)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.8.2.2)
Requirement already satisfied: matplotlib>=3.3.3 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (3.7.1)
Requirement already satisfied: hvplot>=0.7.3 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (0.8.3)
Requirement already satisfied: panel>=0.12.6 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (0.14.4)
Requirement already satisfied: bokeh>=2.4.2 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (2.4.3)
Requirement already satisfied: xlrd in /usr/local/lib/python3.10/dist-packages (from AutoViz) (2.0.1)
Requirement already satisfied: seaborn>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (0.12.2)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from AutoViz) (7.34.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from AutoViz) (3.8.1)
Requirement already satisfied: xgboost>=0.82 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.7.5)
Requirement already satisfied: textblob in /usr/local/lib/python3.10/dist-packages (from AutoViz) (0.17.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.22.4)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (4.5.0)
Requirement already satisfied: holoviews>=1.14.6 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.15.4)
Requirement already satisfied: jupyter in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.0.0)
Requirement already satisfied: fsspec>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from AutoViz) (2023.4.0)
Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (from AutoViz) (2.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.5.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from AutoViz) (0.13.5)
Requirement already satisfied: pyamg in /usr/local/lib/python3.10/dist-packages (from AutoViz) (5.0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from AutoViz) (1.2.2)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from bokeh>=2.4.2->AutoViz) (8.4.0)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from bokeh>=2.4.2->AutoViz) (3.1.2)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.10/dist-packages (from bokeh>=2.4.2->AutoViz) (23.1)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.10/dist-packages (from bokeh>=2.4.2->AutoViz) (6.0)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.10/dist-packages (from bokeh>=2.4.2->AutoViz) (6.2)
Requirement already satisfied: colorcet in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.14.6->AutoViz) (3.0.1)
Requirement already satisfied: param<2.0,>=1.9.3 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.14.6->AutoViz) (1.13.0)
Requirement already satisfied: pyviz-comms>=0.7.4 in /usr/local/lib/python3.10/dist-packages (from holoviews>=1.14.6->AutoViz) (2.2.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.3->AutoViz) (4.39.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.3->AutoViz) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.3->AutoViz) (1.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.3->AutoViz) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.3->AutoViz) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.3.3->AutoViz) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->AutoViz) (2022.7.1)
Requirement already satisfied: tqdm>=4.48.0 in /usr/local/lib/python3.10/dist-packages (from panel>=0.12.6->AutoViz) (4.65.0)
Requirement already satisfied: setuptools>=42 in /usr/local/lib/python3.10/dist-packages (from panel>=0.12.6->AutoViz) (67.7.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from panel>=0.12.6->AutoViz) (2.27.1)
Requirement already satisfied: markdown in /usr/local/lib/python3.10/dist-packages (from panel>=0.12.6->AutoViz) (3.4.3)
Requirement already satisfied: pyct>=0.4.4 in /usr/local/lib/python3.10/dist-packages (from panel>=0.12.6->AutoViz) (0.5.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from panel>=0.12.6->AutoViz) (6.0.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost>=0.82->AutoViz) (1.10.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (0.18.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (0.7.5)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (2.14.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (5.7.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (3.0.38)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->AutoViz) (0.2.0)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.10/dist-packages (from jupyter->AutoViz) (6.1.0)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (from jupyter->AutoViz) (7.7.1)
Requirement already satisfied: qtconsole in /usr/local/lib/python3.10/dist-packages (from jupyter->AutoViz) (5.4.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.10/dist-packages (from jupyter->AutoViz) (6.5.4)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.10/dist-packages (from jupyter->AutoViz) (5.5.6)
Requirement already satisfied: notebook in /usr/local/lib/python3.10/dist-packages (from jupyter->AutoViz) (6.4.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->AutoViz) (1.2.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->AutoViz) (8.1.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->AutoViz) (2022.10.31)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->AutoViz) (3.1.0)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from statsmodels->AutoViz) (0.5.3)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->AutoViz) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.9->bokeh>=2.4.2->AutoViz) (2.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.2->statsmodels->AutoViz) (1.16.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->AutoViz) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->AutoViz) (0.2.6)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->panel>=0.12.6->AutoViz) (0.5.1)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->AutoViz) (0.2.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->AutoViz) (6.1.12)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->jupyter->AutoViz) (3.6.4)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->jupyter->AutoViz) (3.0.7)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (0.7.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (1.5.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (0.4)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (0.2.2)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (0.7.1)
Requirement already satisfied: nbformat>=5.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (5.8.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (4.9.2)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (1.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (4.11.2)
Requirement already satisfied: jupyter-core>=4.7 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->AutoViz) (5.3.0)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->AutoViz) (0.16.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->AutoViz) (23.2.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->AutoViz) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->AutoViz) (0.17.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->AutoViz) (21.3.0)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->AutoViz) (1.5.6)
Requirement already satisfied: qtpy>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from qtconsole->jupyter->AutoViz) (2.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=0.12.6->AutoViz) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=0.12.6->AutoViz) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=0.12.6->AutoViz) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->panel>=0.12.6->AutoViz) (2022.12.7)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.7->nbconvert->jupyter->AutoViz) (3.3.0)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1->nbconvert->jupyter->AutoViz) (4.3.3)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1->nbconvert->jupyter->AutoViz) (2.16.3)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->notebook->jupyter->AutoViz) (21.2.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert->jupyter->AutoViz) (2.4.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter->AutoViz) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter->AutoViz) (0.19.3)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter->AutoViz) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter->AutoViz) (2.21)

In [2]:
!pip install xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.10/dist-packages (2.0.1)

In [3]:
!pip install sweetviz

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sweetviz in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (4.65.0)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.5.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.22.4)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (3.7.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.10.1)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (3.1.2)
Requirement already satisfied: importlib-resources>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (5.12.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.1->sweetviz) (2.1.2)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.39.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.0.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (23.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.16.0)

In [4]:
!pip install optuna

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: optuna in /usr/local/lib/python3.10/dist-packages (3.1.1)
Requirement already satisfied: cmaes>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from optuna) (0.9.1)
Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.10)
Requirement already satisfied: colorlog in /usr/local/lib/python3.10/dist-packages (from optuna) (6.7.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (1.10.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.65.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.22.4)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (23.1)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (1.2.4)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna) (2.0.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.1.2)

In [5]:
!pip install keras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (2.12.0)

In [6]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.12.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.32.0)
Requirement already satisfied: numpy<1.24,>=1.22 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.22.4)
Requirement already satisfied: tensorboard<2.13,>=2.12 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.12.2)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.3.3)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.54.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: jax>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.8)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.1)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.5.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.0)
Requirement already satisfied: keras<2.13,>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.40.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow) (1.10.1)
Requirement already satisfied: ml-dtypes>=0.0.3 in /usr/local/lib/python3.10/dist-packages (from jax>=0.3.15->tensorflow) (0.1.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.27.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (1.8.1)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (1.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (0.7.0)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.3.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (3.4.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.17.3)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (0.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (5.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (2.0.12)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow) (2.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow) (3.2.2)

In [7]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.13.1)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.10.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.0.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.39.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (23.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.2)

In [8]:
!pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.0)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.13.5)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.10.1)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.22.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)

In [9]:
# import helpful functions 
import pandas as pd #To work with dataset
import numpy as np #Math library
import matplotlib.gridspec as gridspec
import seaborn as sns #Graph library that use matplot in background
import matplotlib.pyplot as plt #to plot some parameters in seaborn
import warnings
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PowerTransformer, StandardScaler,Normalizer,RobustScaler,MaxAbsScaler,MinMaxScaler,QuantileTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier
# Import StandardScaler from scikit-learn
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline, Pipeline

from sklearn.manifold import TSNE
# Import train_test_split()
# Metrics
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.metrics import make_scorer
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_curve
from datetime import datetime, date
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.linear_model import LinearRegression, RidgeCV

#import lightgbm as lgbm
from catboost import CatBoostRegressor
import tensorflow as tf 
#from keras import layers
#from keras import EarlyStopping
#from keras import LearningRateScheduler
#import smogn
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.kernel_ridge import KernelRidge
from sklearn.ensemble import GradientBoostingRegressor,RandomForestRegressor
# For training random forest model
#import lightgbm as lgb
from scipy import sparse
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans 
# Model selection
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression,f_classif
from sklearn.feature_selection import mutual_info_regression

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from itertools import combinations
#import smong 

import category_encoders as ce
import optuna 
from tensorflow import keras
from sklearn.metrics import mean_absolute_error as mae
from sklearn.model_selection import GroupKFold,KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import mean_squared_error
import xgboost as xgb
from optuna import Trial, visualization
from optuna.samplers import TPESampler
import os
import time
from sklearn import metrics#
warnings.filterwarnings('ignore')
#import klib
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [10]:
cd /content/gdrive/MyDrive/Colab Notebooks

/content/gdrive/MyDrive/Colab Notebooks

In [11]:
# load the data 
train = pd.read_csv('train.csv')
print(train.head(10))
pressure_values = np.sort( train.pressure.unique() )
test = pd.read_csv('test.csv')
#submission = pd.read_csv('/content/sample_submission.csv')

   id  breath_id   R   C  time_step       u_in  u_out   pressure
0   1          1  20  50   0.000000   0.083334      0   5.837492
1   2          1  20  50   0.033652  18.383041      0   5.907794
2   3          1  20  50   0.067514  22.509278      0   7.876254
3   4          1  20  50   0.101542  22.808822      0  11.742872
4   5          1  20  50   0.135756  25.355850      0  12.234987
5   6          1  20  50   0.169698  27.259866      0  12.867706
6   7          1  20  50   0.203708  27.127486      0  14.695562
7   8          1  20  50   0.237723  26.807732      0  15.890699
8   9          1  20  50   0.271776  27.864715      0  15.539188
9  10          1  20  50   0.305732  28.313036      0  15.750094

In [12]:
def add_features(x_train):
    # shift time,uin-after,u-out-after by one by default 
    # shift by one for x_train,x_test
    # shift time,uin-after,u-out-after by one by default 
    # shift by one for x_train,x_test
    x_train['time_after'] = data[['time_step_std']].shift(1)
    x_train['uin_after'] = data[['un_in_std']].shift(1)
    x_train['u_out_after'] = data[['u_out']].shift(1)
    x_train['time_after2'] = data[['time_step_std']].shift(2)
    x_train['uin_after2'] = data[['un_in_std']].shift(2)
    x_train['u_out_after2'] = data[['u_out']].shift(2)
    x_train['time_after3'] = data[['time_step_std']].shift(3)
    x_train['uin_after3'] = data[['un_in_std']].shift(3)
    x_train['u_out_after3'] = data[['u_out']].shift(3)
    x_train['time_after4'] = data[['time_step_std']].shift(4)
    x_train['uin_after4'] = data[['un_in_std']].shift(4)
    x_train['u_out_after4'] = data[['u_out']].shift(4)
    x_train['time_after5'] = data[['time_step_std']].shift(5)
    x_train['uin_after5'] = data[['un_in_std']].shift(5)
    x_train['u_out_after5'] = data[['u_out']].shift(5)   
    x_train['time_step_back'] = data[['time_step_std']].shift(-1)
    x_train['u_in_back'] = data[['un_in_std']].shift(-1)
    x_train['uout_back'] = data[['u_out']].shift(-1)
    x_train['time_step_back2'] = data[['time_step_std']].shift(-2)
    x_train['u_in_back2'] = data[['un_in_std']].shift(-2)
    x_train['uout_back2'] = data[['u_out']].shift(-2)
    x_train['time_step_back3'] = data[['time_step_std']].shift(-3)
    x_train['u_in_back3'] = data[['un_in_std']].shift(-3)
    x_train['uout_back3'] = data[['u_out']].shift(-3)
    x_train['time_step_back4'] = data[['time_step_std']].shift(-4)
    x_train['u_in_bac4'] = data[['un_in_std']].shift(-4)
    x_train['uout_back4'] = data[['u_out']].shift(-4)
    x_train['time_step_back5'] = data[['time_step_std']].shift(-5)
    x_train['u_in_bac5'] = data[['un_in_std']].shift(-5)
    x_train['uout_back5'] = data[['u_out']].shift(-5)
    print("step 1- completed")
    #The thinking behind this is that the pressure in the lungs is proportional to 
    #how much air has actually been pumped into them. Obviously this feature is not useful when breathing out,
    #but as the expiratory phase is not scored we are ok.
    #In other words, the pressure would be correlated to the integral of valve opening
    
    x_train['u_in_cumsum'] = data[['u_in']].cumsum()
    x_train['time_step_cumsum'] = data[['time_step_std']].cumsum()
    x_train['last_value_u_in'] = data[['u_in']].transform('last')
    x_train['breath_id__u_in__max'] = data[['u_in']].transform('max')
    x_train['breath_id__u_out__max'] =data[['u_out']].transform('max')
    x_train['breath_id__u_in__mean'] =data[['u_in']].transform('mean')
    x_train['breath_id__u_in__diffmax'] = x_train.groupby(['breath_id'])['u_in'].transform('max') - x_train['u_in']
    x_train['breath_id__u_in__diffmean'] = x_train.groupby(['breath_id'])['u_in'].transform('mean') - x_train['u_in']
    print("Step-2...Completed")
    
    # difference between consequitive values
    x_train['u_in_diff1'] = x_train['u_in'] - x_train['uin_after']
    x_train['u_out_diff1'] = x_train['u_out']- x_train['u_out_after']
    x_train['u_in_diff2'] = x_train['u_in'] - x_train['uin_after2']
    x_train['u_out_diff2'] = x_train['u_out'] - x_train['u_out_after2']
    print("Step-3...Completed")
    # dummy vARIABLES  
    x_train['R'] = x_train['R'].astype(str)
    x_train['C'] = x_train['C'].astype(str)
    x_train['R__C'] =  x_train["R"].astype(str) + '__' +  x_train["C"].astype(str)
    print("Step-4...Completed")
    x_train['cross']= x_train['u_in'] * x_train['u_out']
    x_train['cross2']= x_train['time_step'] * x_train['u_out']
    x_train['area'] = x_train['time_step'] * x_train['u_in']
    x_train['area'] = x_train.groupby('breath_id')['area'].cumsum()
    x_train['time_step_cumsum'] = x_train.groupby(['breath_id'])['time_step'].cumsum()
    x_train['u_in_cumsum'] = (x_train['u_in']).groupby(x_train['breath_id']).cumsum()
    print("Step-5...Completed")
    
    # ewm mean
    x_train['time_step_diff'] = x_train.groupby('breath_id')['time_step'].diff().fillna(0)
    x_train['ewm_u_in_mean'] = (x_train.groupby('breath_id')['u_in'].ewm(halflife=9).mean().reset_index(level=0,drop=True))
    # rolling window 
    x_train[["15_in_sum","15_in_min","15_in_max","15_in_mean"]] = (x_train.groupby('breath_id')['u_in'].rolling(window=15,min_periods=1).agg({"15_in_sum":"sum", "15_in_min":"min",  "15_in_max":"max","15_in_mean":"mean"}).reset_index(level=0,drop=True))
    print("Step-6...Completed")
    x_train = pd.get_dummies(x_train)
    x_train['u_in_lagback_diff1'] = x_train['u_in'] - x_train['u_in_back']
    x_train['u_out_lagback_diff1'] = x_train['u_out'] - x_train['uout_back']
    x_train['u_in_lagback_diff2'] = x_train['u_in'] - x_train['u_in_back2']
    x_train['u_out_lagback_diff2'] = x_train['u_out'] - x_train['uout_back2']
    x_train=x_train.fillna(0)

    print("Step-7...Completed")
    
    
    return x_train

In [13]:
data = train.groupby(["breath_id"])
#data_tst=test.groupby(["breath_id"])
train['un_in_std'] = data['u_in'].transform(lambda x: (x - x.mean()) / x.std())
train['time_step_std'] = data['time_step'].transform(lambda x: (x - x.mean()) / x.std())
print(train.head(10))

   id  breath_id   R   C  time_step       u_in  u_out   pressure  un_in_std  \
0   1          1  20  50   0.000000   0.083334      0   5.837492  -0.993975
1   2          1  20  50   0.033652  18.383041      0   5.907794   0.813641
2   3          1  20  50   0.067514  22.509278      0   7.876254   1.221224
3   4          1  20  50   0.101542  22.808822      0  11.742872   1.250813
4   5          1  20  50   0.135756  25.355850      0  12.234987   1.502404
5   6          1  20  50   0.169698  27.259866      0  12.867706   1.690480
6   7          1  20  50   0.203708  27.127486      0  14.695562   1.677403
7   8          1  20  50   0.237723  26.807732      0  15.890699   1.645819
8   9          1  20  50   0.271776  27.864715      0  15.539188   1.750226
9  10          1  20  50   0.305732  28.313036      0  15.750094   1.794510

   time_step_std
0      -1.699182
1      -1.656655
2      -1.613864
3      -1.570863
4      -1.527627
5      -1.484734
6      -1.441756
7      -1.398771
8      -1.355737
9      -1.312828

In [14]:
y=train['pressure']
bins=[np.percentile(y,0),np.percentile(y,10),np.percentile(y,90),np.percentile(y,100)]
labels1 = [ 'Low', 'Medium', 'High']
trainessai=train.copy()
# Bin the continuous variable ConvertedSalary using these boundaries
trainessai['target_binned'] = pd.cut(trainessai['pressure'],bins=bins,labels=labels1 )
print(trainessai.head(20))
trainessai.tail(10)

    id  breath_id   R   C  time_step       u_in  u_out   pressure  un_in_std  \
0    1          1  20  50   0.000000   0.083334      0   5.837492  -0.993975
1    2          1  20  50   0.033652  18.383041      0   5.907794   0.813641
2    3          1  20  50   0.067514  22.509278      0   7.876254   1.221224
3    4          1  20  50   0.101542  22.808822      0  11.742872   1.250813
4    5          1  20  50   0.135756  25.355850      0  12.234987   1.502404
5    6          1  20  50   0.169698  27.259866      0  12.867706   1.690480
6    7          1  20  50   0.203708  27.127486      0  14.695562   1.677403
7    8          1  20  50   0.237723  26.807732      0  15.890699   1.645819
8    9          1  20  50   0.271776  27.864715      0  15.539188   1.750226
9   10          1  20  50   0.305732  28.313036      0  15.750094   1.794510
10  11          1  20  50   0.339675  26.866758      0  17.296741   1.651649
11  12          1  20  50   0.373680  26.762803      0  17.226439   1.641381
12  13          1  20  50   0.407650  27.993274      0  16.171907   1.762925
13  14          1  20  50   0.441804  26.789898      0  17.367044   1.644057
14  15          1  20  50   0.476103  25.634070      0  18.070065   1.529886
15  16          1  20  50   0.509996  26.280195      0  17.156137   1.593709
16  17          1  20  50   0.544041  24.726714      0  18.280971   1.440259
17  18          1  20  50   0.578179  23.467889      0  18.773086   1.315914
18  19          1  20  50   0.612109  23.858434      0  17.859159   1.354492
19  20          1  20  50   0.646055  21.883404      0  19.124597   1.159401

    time_step_std target_binned
0       -1.699182        Medium
1       -1.656655        Medium
2       -1.613864        Medium
3       -1.570863        Medium
4       -1.527627        Medium
5       -1.484734        Medium
6       -1.441756        Medium
7       -1.398771        Medium
8       -1.355737        Medium
9       -1.312828        Medium
10      -1.269934        Medium
11      -1.226961        Medium
12      -1.184033        Medium
13      -1.140873        Medium
14      -1.097530        Medium
15      -1.054699        Medium
16      -1.011676        Medium
17      -0.968536        Medium
18      -0.925658        Medium
19      -0.882761        Medium

,id,breath_id,R,C,time_step,u_in,u_out,pressure,un_in_std,time_step_std,target_binned
6035990,6035991,125749,50,10,2.337683,1.367263,1,4.009636,-0.636359,1.312672,Low
6035991,6035992,125749,50,10,2.371120,1.362261,1,4.009636,-0.637257,1.355747,Low
6035992,6035993,125749,50,10,2.404458,1.357586,1,4.009636,-0.638097,1.398696,Low
6035993,6035994,125749,50,10,2.437786,1.353205,1,4.009636,-0.638883,1.441631,Low
6035994,6035995,125749,50,10,2.471192,1.420711,1,3.939334,-0.626762,1.484666,Low
6035995,6035996,125749,50,10,2.504603,1.489714,1,3.869032,-0.614373,1.527709,Low
6035996,6035997,125749,50,10,2.537961,1.488497,1,3.869032,-0.614591,1.570683,Low
6035997,6035998,125749,50,10,2.571408,1.558978,1,3.798729,-0.601936,1.613771,Low
6035998,6035999,125749,50,10,2.604744,1.272663,1,4.079938,-0.653345,1.656718,Low
6035999,6036000,125749,50,10,2.638017,1.482739,1,3.869032,-0.615625,1.699583,Low

In [15]:

y=trainessai['target_binned'].copy()
X=trainessai.copy().drop('target_binned', axis = 1)

In [16]:
#y=y.to_numpy()

In [17]:
print(X)

              id  breath_id   R   C  time_step       u_in  u_out   pressure  \
0              1          1  20  50   0.000000   0.083334      0   5.837492
1              2          1  20  50   0.033652  18.383041      0   5.907794
2              3          1  20  50   0.067514  22.509278      0   7.876254
3              4          1  20  50   0.101542  22.808822      0  11.742872
4              5          1  20  50   0.135756  25.355850      0  12.234987
...          ...        ...  ..  ..        ...        ...    ...        ...
6035995  6035996     125749  50  10   2.504603   1.489714      1   3.869032
6035996  6035997     125749  50  10   2.537961   1.488497      1   3.869032
6035997  6035998     125749  50  10   2.571408   1.558978      1   3.798729
6035998  6035999     125749  50  10   2.604744   1.272663      1   4.079938
6035999  6036000     125749  50  10   2.638017   1.482739      1   3.869032

         un_in_std  time_step_std
0        -0.993975      -1.699182
1         0.813641      -1.656655
2         1.221224      -1.613864
3         1.250813      -1.570863
4         1.502404      -1.527627
...            ...            ...
6035995  -0.614373       1.527709
6035996  -0.614591       1.570683
6035997  -0.601936       1.613771
6035998  -0.653345       1.656718
6035999  -0.615625       1.699583

[6036000 rows x 10 columns]

In [18]:
X=add_features(X)
X.head(10)
type(X)

step 1- completed
Step-2...Completed
Step-3...Completed
Step-4...Completed
Step-5...Completed
Step-6...Completed
Step-7...Completed

pandas.core.frame.DataFrame

In [19]:
X.head(10)
X.columns

Index(['id', 'breath_id', 'time_step', 'u_in', 'u_out', 'pressure',
       'un_in_std', 'time_step_std', 'time_after', 'uin_after', 'u_out_after',
       'time_after2', 'uin_after2', 'u_out_after2', 'time_after3',
       'uin_after3', 'u_out_after3', 'time_after4', 'uin_after4',
       'u_out_after4', 'time_after5', 'uin_after5', 'u_out_after5',
       'time_step_back', 'u_in_back', 'uout_back', 'time_step_back2',
       'u_in_back2', 'uout_back2', 'time_step_back3', 'u_in_back3',
       'uout_back3', 'time_step_back4', 'u_in_bac4', 'uout_back4',
       'time_step_back5', 'u_in_bac5', 'uout_back5', 'u_in_cumsum',
       'time_step_cumsum', 'last_value_u_in', 'breath_id__u_in__max',
       'breath_id__u_out__max', 'breath_id__u_in__mean',
       'breath_id__u_in__diffmax', 'breath_id__u_in__diffmean', 'u_in_diff1',
       'u_out_diff1', 'u_in_diff2', 'u_out_diff2', 'cross', 'cross2', 'area',
       'time_step_diff', 'ewm_u_in_mean', '15_in_sum', '15_in_min',
       '15_in_max', '15_in_mean', 'R_20', 'R_5', 'R_50', 'C_10', 'C_20',
       'C_50', 'R__C_20__10', 'R__C_20__20', 'R__C_20__50', 'R__C_50__10',
       'R__C_50__20', 'R__C_50__50', 'R__C_5__10', 'R__C_5__20', 'R__C_5__50',
       'u_in_lagback_diff1', 'u_out_lagback_diff1', 'u_in_lagback_diff2',
       'u_out_lagback_diff2'],
      dtype='object')

In [20]:
X.head(10)

,id,breath_id,time_step,u_in,u_out,pressure,un_in_std,time_step_std,time_after,uin_after,...,R__C_50__10,R__C_50__20,R__C_50__50,R__C_5__10,R__C_5__20,R__C_5__50,u_in_lagback_diff1,u_out_lagback_diff1,u_in_lagback_diff2,u_out_lagback_diff2
0,1,1,0.000000,0.083334,0,5.837492,-0.993975,-1.699182,0.000000,0.000000,...,0,0,0,0,0,0,-0.730307,0.0,-1.137890,0.0
1,2,1,0.033652,18.383041,0,5.907794,0.813641,-1.656655,-1.699182,-0.993975,...,0,0,0,0,0,0,17.161817,0.0,17.132229,0.0
2,3,1,0.067514,22.509278,0,7.876254,1.221224,-1.613864,-1.656655,0.813641,...,0,0,0,0,0,0,21.258465,0.0,21.006874,0.0
3,4,1,0.101542,22.808822,0,11.742872,1.250813,-1.570863,-1.613864,1.221224,...,0,0,0,0,0,0,21.306418,0.0,21.118343,0.0
4,5,1,0.135756,25.355850,0,12.234987,1.502404,-1.527627,-1.570863,1.250813,...,0,0,0,0,0,0,23.665371,0.0,23.678447,0.0
5,6,1,0.169698,27.259866,0,12.867706,1.690480,-1.484734,-1.527627,1.502404,...,0,0,0,0,0,0,25.582462,0.0,25.614047,0.0
6,7,1,0.203708,27.127486,0,14.695562,1.677403,-1.441756,-1.484734,1.690480,...,0,0,0,0,0,0,25.481667,0.0,25.377260,0.0
7,8,1,0.237723,26.807732,0,15.890699,1.645819,-1.398771,-1.441756,1.677403,...,0,0,0,0,0,0,25.057506,0.0,25.013222,0.0
8,9,1,0.271776,27.864715,0,15.539188,1.750226,-1.355737,-1.398771,1.645819,...,0,0,0,0,0,0,26.070205,0.0,26.213066,0.0
9,10,1,0.305732,28.313036,0,15.750094,1.794510,-1.312828,-1.355737,1.750226,...,0,0,0,0,0,0,26.661387,0.0,26.671655,0.0

In [21]:
X.drop(['id', 'breath_id','pressure'], axis=1, inplace=True)
print(X.head(5))

   time_step       u_in  u_out  un_in_std  time_step_std  time_after  \
0   0.000000   0.083334      0  -0.993975      -1.699182    0.000000
1   0.033652  18.383041      0   0.813641      -1.656655   -1.699182
2   0.067514  22.509278      0   1.221224      -1.613864   -1.656655
3   0.101542  22.808822      0   1.250813      -1.570863   -1.613864
4   0.135756  25.355850      0   1.502404      -1.527627   -1.570863

   uin_after  u_out_after  time_after2  uin_after2  ...  R__C_50__10  \
0   0.000000          0.0     0.000000    0.000000  ...            0
1  -0.993975          0.0     0.000000    0.000000  ...            0
2   0.813641          0.0    -1.699182   -0.993975  ...            0
3   1.221224          0.0    -1.656655    0.813641  ...            0
4   1.250813          0.0    -1.613864    1.221224  ...            0

   R__C_50__20  R__C_50__50  R__C_5__10  R__C_5__20  R__C_5__50  \
0            0            0           0           0           0
1            0            0           0           0           0
2            0            0           0           0           0
3            0            0           0           0           0
4            0            0           0           0           0

   u_in_lagback_diff1  u_out_lagback_diff1  u_in_lagback_diff2  \
0           -0.730307                  0.0           -1.137890
1           17.161817                  0.0           17.132229
2           21.258465                  0.0           21.006874
3           21.306418                  0.0           21.118343
4           23.665371                  0.0           23.678447

   u_out_lagback_diff2
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0

[5 rows x 75 columns]

In [22]:
from sklearn.preprocessing import RobustScaler
scaler_X = RobustScaler()
X= scaler_X.fit_transform(X)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [24]:
type(X_train)

numpy.ndarray

In [25]:

# Check if the NumPy array contains any NaN value
if(np.isnan(X_train).any()):
    print("The Array contain NaN values")
else:
    print("The Array does not contain NaN values")

The Array does not contain NaN values

In [26]:
if(np.isnan(X_test).any()):
    print("The Array contain NaN values")
else:
    print("The Array does not contain NaN values")

The Array does not contain NaN values

In [27]:
X_train.shape

(4828800, 75)

In [28]:
y_train.shape

(4828800,)

In [29]:
print(y_train.isnull().any())

True

In [30]:
y_train.isnull().values.sum()

2

In [31]:
!pip install sklearn_pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sklearn_pandas in /usr/local/lib/python3.10/dist-packages (2.2.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.10/dist-packages (from sklearn_pandas) (1.22.4)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.10/dist-packages (from sklearn_pandas) (1.5.3)
Requirement already satisfied: scikit-learn>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from sklearn_pandas) (1.2.2)
Requirement already satisfied: scipy>=1.5.1 in /usr/local/lib/python3.10/dist-packages (from sklearn_pandas) (1.10.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->sklearn_pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.4->sklearn_pandas) (2.8.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23.0->sklearn_pandas) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23.0->sklearn_pandas) (3.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.1.4->sklearn_pandas) (1.16.0)

In [32]:
# fix nans in y_train 
# Filling NaN in Categorical data
#1. Function to replace NAN values with mode value
def impute_nan_most_frequent_category(ColName):
    # .mode()[0] - gives first category name
     most_frequent_category=ColName.mode()[0]
    
    # replace nan values with most occured category
     
     ColName.fillna(most_frequent_category,inplace=True)
     return ColName

In [33]:
#2. Call function to impute most occured category
y_train=impute_nan_most_frequent_category(y_train)

In [34]:
y_train.isnull().values.sum()

0

In [35]:
type(y_train)

pandas.core.series.Series

In [36]:
len(y_test)

1207200

In [37]:
!pip install thundersvm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: thundersvm in /usr/local/lib/python3.10/dist-packages (0.3.12)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from thundersvm) (1.22.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from thundersvm) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from thundersvm) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->thundersvm) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->thundersvm) (3.1.0)

In [48]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
#from thundersvm import SVC

X_train= pd.DataFrame(X_train)
X_test= pd.DataFrame(X_test)

#X_train=X_train.fillna(0)
#y_train=y_train.fillna(0)
#X_valid=X_test.fillna(0)
#y_valid=y_valid.fillna(0)
X_train=X_train[:2501000]
y_train=y_train[:2501000]
X_test=X_test[:40000]
y_test=y_test[:40000]
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train) 

# Predict y data with classifier: 
y_predict = classifier.predict(X_test)

# Print results: 
print("confusion matrix is")
print(confusion_matrix(y_test, y_predict))
# Evaluate label (subsets) accuracy:
print("accuracy score is")
print(accuracy_score(y_test, y_predict))
print("classification report is")
print(classification_report(y_test, y_predict))

confusion matrix is
[[ 856    0  123]
 [   0  866  240]
 [  96  150 7669]]
accuracy score is
0.9391
classification report is
              precision    recall  f1-score   support

        High       0.90      0.87      0.89       979
         Low       0.85      0.78      0.82      1106
      Medium       0.95      0.97      0.96      7915

    accuracy                           0.94     10000
   macro avg       0.90      0.88      0.89     10000
weighted avg       0.94      0.94      0.94     10000

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
# Initialize classifier:
gnb = GaussianNB()

# Train the classifier:
model = gnb.fit(X_train,y_train )
# Make predictions with the classifier:
predictive_labels = gnb.predict(X_test)
print(predictive_labels)

# Evaluate label (subsets) accuracy:
print(accuracy_score(y_test, predictive_labels))

['Low' 'High' 'Low' ... 'Low' 'Low' 'High']
0.3352

In [50]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr')
# Train the classifier:
model = LR.fit(X_train,y_train )
# Make predictions with the classifier:
predictive_labels_log = LR.predict(X_test)
print(predictive_labels_log)

# Evaluate label (subsets) accuracy:
print(accuracy_score(y_test, predictive_labels_log))

['Medium' 'Medium' 'Medium' ... 'Medium' 'Medium' 'High']
0.867

In [51]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X_train,y_train )
pre=clf.predict(X_test)
# Evaluate label (subsets) accuracy:
print(accuracy_score(y_test, pre))

0.8718